<a href="https://colab.research.google.com/github/Danilov-Aleksandr/CV_Korpus/blob/master/%D0%97%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%B5%D1%80%D1%86%D0%B5%D0%BF%D1%82%D1%80%D0%BE%D0%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Сначала немного простых задач, для разминки

In [42]:
#Импортируем Numpy
import numpy as np

In [ ]:
# найти индекс максимального значения в одномерном массиве:
a = np.array([0.2, 0.4, -0.1, 0.5, 0.33, 0.9, 0.875, 0.14])
a.argmax()

5

Формула Z - масштабирования. Где где X - среднее значение, S - стандартное отклонение вычисленные для множества данных x
![Замещающий текст](https://wikimedia.org/api/rest_v1/media/math/render/svg/3fae59e6af64fb5c102229fcf9034175bec85372)

In [ ]:
#создать 5х5 массив из рандомных значений и сделать Z-масштабирование
x = np.random.random((5,5))
#

In [ ]:
#сделать все значения меньше 0 равными 0, а больше 10 равными 10
a = np.random.randint(-2, 12, (4,5))
np.clip(a, 0, 10)

array([[ 2,  0, 10,  6, 10],
       [ 4,  3,  0,  5,  2],
       [10,  2, 10,  0,  2],
       [ 7,  6,  6,  9,  3]])

In [ ]:
#представим что у вас есть ч/б картинка размером 28x28, нужно добавить количество каналов = 1
image = np.random.random(784).reshape(28,28)
image_with_channel = np.expand_dims(image, axis=0)
image_with_channel.shape


(1, 28, 28)

In [ ]:
#как одной функцией удалить сразу все единичные размерности
a = np.random.random(784).reshape(1,1,28,1,1,28)
a = a.reshape(28, 28)
a.shape
#

(28, 28)

In [ ]:
#создайте нулевой массив по форме другого:
a = np.arange(10).reshape(5,2)
labels = np.zeros_like(a)
labels.shape

(5, 2)

Теперь давайте создадим с вами небольшую нейронную сеть с помощью Numpy и обучим ее. Это тот самый перцептрон, с которым мы подробнее познакомимся на следующем занятии.

![Замещающий текст](https://neerc.ifmo.ru/wiki/images/a/a5/%D0%98%D1%81%D0%BA%D1%83%D1%81%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BD%D0%B5%D0%B9%D1%80%D0%BE%D0%BD_%D1%81%D1%85%D0%B5%D0%BC%D0%B0.png)

Воспользуемся фукнцией активации сигмоид.

![Замещающий текст](https://habrastorage.org/files/150/8ef/062/1508ef06235444c3bc74a942812b4eb7.png)

In [55]:
#Напишем фукнцию активации. Возьмем сигмоиду.
def sigmoid(x):
    return 1/(1+np.exp(-x))



Так будут выглядеть данные нашей игрушечной сети:

![Замещающий текст](https://sun9-33.userapi.com/c857324/v857324999/1f20d7/GVRf86Zc9Kw.jpg)

Видите закономерность? Попробуйте найти.

In [56]:
#создайте 2 numpy array: один для входов, другой для выходов

# набор входных данных
X = np.array([[0,0,1],
              [1,1,1],
              [1,0,1],
              [0,1,1]])
    
# выходные данные        
y = np.array([0,1,1,0]).reshape(4, 1)


# Установим сид, для лучшей воспроизводимости экспериментов
np.random.seed(42)

# инициализируем веса случайным образом со средним 0 в диапозоне [-1, 1]. Shape (3,1)
weights = np.random.random((3,1))


print(weights)

[[0.37454012]
 [0.95071431]
 [0.73199394]]


In [57]:
y

array([[0],
       [1],
       [1],
       [0]])

In [58]:
X.shape

(4, 3)

Проверим, работает ли все без обучения?

In [59]:
inputs = X
# прогнать наши выхода через перцептрон, сначала перемножить с весами, а потом все это в сигмоиду
outputs = sigmoid(np.matmul(inputs, weights))
print(outputs)

[[0.67524268]
 [0.88667798]
 [0.75148239]
 [0.84326281]]


Обучим нейронку, применив метод обратного распространения ошибки

In [60]:
for iter in range(10000):
    # прямое распространение (делаем тоже самое что в ячейке выше)
    inputs = X
    outputs = sigmoid(np.matmul(inputs, weights))
    #print(outputs)
    #print(np.matmul(inputs, weights))
    # насколько мы ошиблись (из наших меток (y) нужно вычесть полученные выходы)
    error = y - outputs
    
    #Магия градиентов (будет понятнее после следующего занятия, пока примите это как есть)
    delta = error * (outputs * (1-outputs))
    adjust = np.matmul(inputs.T, delta)

    # обновим веса (нужно прибавить к весу значение adjust и это будет новым весом)
    weights = weights + adjust

#Проверим результаты
#Должно получиться близко к 1 там, где 1, и близко к 0, где ноль.
print("Выходные данные после тренировки: ")
print(outputs)


Выходные данные после тренировки: 
[[0.00966731]
 [0.99211766]
 [0.99358907]
 [0.00786534]]


In [50]:
#Попробуем на данных которых сеть не видела

new_inputs = np.array([1,1,0])
#вы знаете что делать, снова прогнать через перцептрон с уже обученными весами.
output = 

print(output)


SyntaxError: ignored